Resource: MedicationRequest
Parent: DomainResource
Id: MedicationRequest
Title: "MedicationRequest"
Description: "An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called \"MedicationRequest\" rather than \"MedicationPrescription\" or \"MedicationOrder\" to generalize the use across inpatient and outpatient settings, including care plans, etc., and to harmonize with workflow patterns."
* identifier 0..* Identifier "External ids for this request" "Identifiers associated with this medication request that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are business identifiers assigned to this resource by the performer or other systems and remain constant as the resource is updated and propagates from server to server."
* subject 1..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Group) "Who or group medication request is for" "A link to a resource representing the person or set of individuals to whom the medication will be given."
* reasonCode 0..* CodeableConcept "Reason or indication for ordering or not ordering the medication" "The reason or the indication for ordering or not ordering the medication."
* reasonCode from http://hl7.org/fhir/ValueSet/condition-code (example)
* reasonReference 0..* Reference(http://hl7.org/fhir/StructureDefinition/Condition or http://hl7.org/fhir/StructureDefinition/Observation) "Condition or observation that supports why the prescription is being written" "Condition or observation that supports why the medication was ordered."
* medication[x] 1..1 SU CodeableConcept or Reference(http://hl7.org/fhir/StructureDefinition/Medication) "Medication to be taken" "Identifies the medication being requested. This is a link to a resource that represents the medication which may be the details of the medication or simply an attribute carrying a code that identifies the medication from a known list of medications."
* medication[x] from http://hl7.org/fhir/ValueSet/medication-codes (example)
* encounter 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Encounter) "Encounter created as part of encounter/admission/stay" "The Encounter during which this [x] was created or to which the creation of this record is tightly associated."
* status 1..1 ?! SU code "active | on-hold | cancelled | completed | entered-in-error | stopped | draft | unknown" "A code specifying the current state of the order.  Generally, this will be active or completed state."
* status from http://hl7.org/fhir/ValueSet/medicationrequest-status|4.0.1 (required)
* priority 0..1 SU code "routine | urgent | asap | stat" "Indicates how quickly the Medication Request should be addressed with respect to other requests."
* priority from http://hl7.org/fhir/ValueSet/request-priority|4.0.1 (required)
* supportingInformation 0..* Reference(http://hl7.org/fhir/StructureDefinition/Resource) "Information to support ordering of the medication" "Include additional information (for example, patient height and weight) that supports the ordering of the medication."
* authoredOn 0..1 SU dateTime "When request was initially authored" "The date (and perhaps time) when the prescription was initially written or authored on."
* requester 0..1 SU Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/RelatedPerson or http://hl7.org/fhir/StructureDefinition/Device) "Who/What requested the Request" "The individual, organization, or device that initiated the request and has responsibility for its activation."
* performer 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Practitioner or http://hl7.org/fhir/StructureDefinition/PractitionerRole or http://hl7.org/fhir/StructureDefinition/Organization or http://hl7.org/fhir/StructureDefinition/Patient or http://hl7.org/fhir/StructureDefinition/Device or http://hl7.org/fhir/StructureDefinition/RelatedPerson or http://hl7.org/fhir/StructureDefinition/CareTeam) "Intended performer of administration" "The specified desired performer of the medication treatment (e.g. the performer of the medication administration)."
* basedOn 0..* SU Reference(http://hl7.org/fhir/StructureDefinition/CarePlan or http://hl7.org/fhir/StructureDefinition/MedicationRequest or http://hl7.org/fhir/StructureDefinition/ServiceRequest or http://hl7.org/fhir/StructureDefinition/ImmunizationRecommendation) "What request fulfills" "A plan or request that is fulfilled in whole or in part by this medication request."
* courseOfTherapyType 0..1 CodeableConcept "Overall pattern of medication administration" "The description of the overall patte3rn of the administration of the medication to the patient."
* courseOfTherapyType from http://hl7.org/fhir/ValueSet/medicationrequest-course-of-therapy (example)
* insurance 0..* Reference(http://hl7.org/fhir/StructureDefinition/Coverage or http://hl7.org/fhir/StructureDefinition/ClaimResponse) "Associated insurance coverage" "Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be required for delivering the requested service."
* note 0..* Annotation "Information about the prescription" "Extra information about the prescription that could not be conveyed by the other attributes."
* dosageInstruction 0..* Dosage "How the medication should be taken" "Indicates how the medication is to be used by the patient."
* dosageInstruction ^comment = "There are examples where a medication request may include the option of an oral dose or an Intravenous or Intramuscular dose.  For example, \"Ondansetron 8mg orally or IV twice a day as needed for nausea\" or \"CompazineÂ® (prochlorperazine) 5-10mg PO or 25mg PR bid prn nausea or vomiting\".  In these cases, two medication requests would be created that could be grouped together.  The decision on which dose and route of administration to use is based on the patient's condition at the time the dose is needed."
* dispenseRequest 0..1 BackboneElement "Medication supply authorization" "Indicates the specific details for the dispense or medication supply part of a medication request (also known as a Medication Prescription or Medication Order).  Note that this information is not always sent with the order.  There may be in some settings (e.g. hospitals) institutional or system support for completing the dispense details in the pharmacy department."
* dispenseRequest.performer 0..1 Reference(http://hl7.org/fhir/StructureDefinition/Organization) "Intended dispenser" "Indicates the intended dispensing Organization specified by the prescriber."
* substitution 0..1 BackboneElement "Any restrictions on medication substitution" "Indicates whether or not substitution can or should be part of the dispense. In some cases, substitution must happen, in other cases substitution must not happen. This block explains the prescriber's intent. If nothing is specified substitution may be done."
* substitution.allowed[x] 1..1 boolean or CodeableConcept "Whether substitution is allowed or not" "True if the prescriber allows a different drug to be dispensed from what was prescribed."
* substitution.allowed[x] from http://terminology.hl7.org/ValueSet/v3-ActSubstanceAdminSubstitutionCode (example)
* substitution.reason 0..1 CodeableConcept "Why should (not) substitution be made" "Indicates the reason for the substitution, or why substitution must or must not be performed."
* substitution.reason from http://terminology.hl7.org/ValueSet/v3-SubstanceAdminSubstitutionReason (example)
* priorPrescription 0..1 Reference(http://hl7.org/fhir/StructureDefinition/MedicationRequest) "An order/prescription that is being replaced" "A link to a resource representing an earlier order related order or prescription."
* detectedIssue 0..* Reference(http://hl7.org/fhir/StructureDefinition/DetectedIssue) "Clinical Issue with action" "Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. Drug-drug interaction, duplicate therapy, dosage alert etc."
* eventHistory 0..* Reference(http://hl7.org/fhir/StructureDefinition/Provenance) "A list of events of interest in the lifecycle" "Links to Provenance records for past versions of this resource or fulfilling request or event resources that identify key state transitions or updates that are likely to be relevant to a user looking at the current version of the resource."